name: oction-unlock-issue
description: |
  This action implements `DELETE` request to `/repos/{owner}/{repo}/issues/{issue_number}/lock`

inputs:
  token:
    description: |
      Token to authenticate the request
    required: true
  owner:
    description: |
      owner parameter
    required: false
  repo:
    description: |
      repo parameter
    required: false
  issue_number:
    description: |
      issue_number parameter
    required: true

runs:
  using: node12
  main: index.js

branding:
  icon: unlock
  color: green
